// Generated by CoffeeScript 1.6.2
(function() {
  var appsocket;

  appsocket = function() {
    var socket;

    console.log('connecting to server');
    socket = io.connect('http://localhost:5000');
    socket.on('connect', function() {
      console.log('connected');
      return socket.emit('adduser', prompt("tell me your name"));
    });
    socket.on('updatechat', function(username, data) {
      console.log('got chat update from #{username} with data #{data}');
      return $('#conversation').append("<b>" + username + ":</b>" + data + "<br />");
    });
    socket.on('updateusers', function(data) {
      console.log('user update');
      $('#users').empty();
      return $.each(data, function(key, value) {
        return $('#users').append("<div>" + key + "</div>");
      });
    });
    return $(function() {
      console.log('register UI callbacks');
      $('#datasend').click(function() {
        var message;

        message = $('#data').val();
        $('#data').val('');
        return socket.emit('chat', message);
      });
      return $('#data').keypress(function(e) {
        if (e.which === 13) {
          return $('#datasend').focus().click();
        }
      });
    });
  };

  this.App || (this.App = {});

  this.App.socket = appsocket();

}).call(this);
